import { PrismaClient, ProductCategory } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database...')

  // ─── CATEGORIES ─────────────────────────────────────────────────────────────
  const categoryData = [
    { id: 'cat-all',        slug: 'all',              name: 'Tất cả',                     description: 'Toàn bộ thực đơn' },
    { id: 'cat-matcha-1',   slug: 'matcha-nghi-thuc', name: 'Matcha Nghi Thức Uji',        description: 'Usucha, Koicha truyền thống' },
    { id: 'cat-matcha-2',   slug: 'matcha-sang-tao',  name: 'Matcha Latte & Sáng Tạo',    description: 'Matcha kết hợp sữa hạt, dừa tươi' },
    { id: 'cat-coffee',     slug: 'ca-phe',           name: 'Cà Phê & Đồ Uống Đặc Sắc',  description: 'Cold Brew, Espresso, fusion' },
    { id: 'cat-dessert',    slug: 'trang-mieng',      name: 'Bánh & Tráng Miệng Zen',     description: 'Tiramisu, Mochi, Japanese desserts' },
    { id: 'cat-equipment',  slug: 'dung-cu',          name: 'Bột Trà & Dụng Cụ',          description: 'Matcha powder, Chasen, gift sets' },
  ]

  for (const cat of categoryData) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    })
  }
  console.log(`✅ ${categoryData.length} categories created`)

  // ─── PRODUCTS ────────────────────────────────────────────────────────────────
  const productData = [
    // MATCHA
    {
      slug: 'matcha-latte-yen-mach',
      name: 'Matcha Latte Yến Mạch Tươi',
      nameEn: 'Matcha Oat Milk Latte',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 65000,
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800',
      description: 'Lớp matcha Uji xanh mướt hòa quyện sữa yến mạch béo mịn, tạo phân tầng nghệ thuật với độ ngọt tự nhiên từ đường hoa dừa',
      descriptionEn: 'Premium Uji matcha blended with creamy oat milk and coconut blossom sugar',
      tags: ['Bestseller', 'Organic', 'Plant-based'],
      isNew: false,
      isBestseller: true,
      inStock: true,
      ingredients: ['Matcha Uji Ceremonial', 'Sữa yến mạch tươi', 'Đường hoa dừa'],
      customIce: true,
      customSugar: true,
      customMilk: ['Yến mạch', 'Hạnh nhân', 'Dừa', 'Sữa tươi'],
      customSize: ['M', 'L'],
    },
    {
      slug: 'usucha-uji-thuan-khiet',
      name: 'Usucha Uji Thuần Khiết',
      nameEn: 'Pure Usucha Uji',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Nghi Thức (Ceremonial)',
      price: 65000,
      image: 'https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=800',
      description: '2g bột Matcha Ceremonial đánh chasen theo nghi thức Nhật Bản, tạo lớp micro-foam mịn màng, vị đắng nhẹ thanh mát',
      descriptionEn: 'Traditional ceremonial matcha whisked to perfection',
      tags: ['Ceremonial', 'Traditional', 'JAS Organic'],
      isNew: false,
      isBestseller: true,
      inStock: true,
      ingredients: ['Matcha Uji Ceremonial 100%', 'Nước suối núi lửa 75-80°C'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'koicha-dam-dac',
      name: 'Koicha Đậm Đặc Thượng Phẩm',
      nameEn: 'Premium Koicha',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Nghi Thức (Ceremonial)',
      price: 75000,
      image: 'https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?w=800',
      description: 'Cấp độ trà đạo cao nhất với 4g bột matcha, kết cấu đặc sệt như siro, hương umami sâu lắng dành cho người sành',
      descriptionEn: 'Thick ceremonial matcha for tea connoisseurs',
      tags: ['Premium', 'Ceremonial', 'For Connoisseurs'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji Ceremonial Grade A', 'Nước suối núi lửa'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'matcha-dua-xiem',
      name: 'Matcha Dừa Xiêm Tươi Mát',
      nameEn: 'Matcha Fresh Coconut',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 62000,
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800',
      description: 'Matcha xanh mát kết hợp nước dừa xiêm tươi ngọt thanh, topping thạch dừa giòn dai, hoàn hảo cho mùa hè',
      descriptionEn: 'Refreshing matcha with fresh young coconut water',
      tags: ['Refreshing', 'Summer', 'Natural Sweetness'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Nước dừa xiêm tươi', 'Thạch dừa'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    // COFFEE
    {
      slug: 'mo-rung-cold-brew',
      name: 'Mơ Rừng Cold Brew',
      nameEn: 'Wild Apricot Cold Brew',
      category: ProductCategory.coffee,
      subcategory: 'Cold Brew Ủ Chậm',
      price: 55000,
      image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800',
      description: 'Cold brew ủ lạnh 16 giờ từ hạt Arabica Cầu Đất, thêm siro mơ rừng Tây Bắc chua ngọt tự nhiên',
      descriptionEn: '16-hour cold brew with wild apricot syrup',
      tags: ['Cold Brew', 'Signature', 'Low Acid'],
      isNew: false,
      isBestseller: true,
      inStock: true,
      ingredients: ['Arabica Cầu Đất', 'Siro mơ rừng', 'Nước mềm ủ lạnh 16h'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-cold-foam-coffee',
      name: 'Matcha Cold Foam Coffee',
      nameEn: 'Matcha Cold Foam Coffee',
      category: ProductCategory.coffee,
      subcategory: 'Cà phê Kết Hợp Matcha',
      price: 68000,
      image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800',
      description: 'Espresso đậm đà kết hợp cold brew, phủ lớp foam matcha xanh mượt mà tạo màu sắc và hương vị độc đáo',
      descriptionEn: 'Espresso topped with creamy matcha cold foam',
      tags: ['Fusion', 'Instagram-worthy', 'Bestseller'],
      isNew: false,
      isBestseller: true,
      inStock: true,
      ingredients: ['Espresso Arabica', 'Cold Brew', 'Matcha Foam'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'ca-phe-muoi-bot-bien',
      name: 'Cà phê Muối Bọt Biển',
      nameEn: 'Sea Salt Coffee',
      category: ProductCategory.coffee,
      subcategory: 'Pha Phin & Espresso',
      price: 48000,
      image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
      description: 'Cà phê phin truyền thống đắng đậm, phủ lớp kem muối biển mặn ngọt độc đáo kiểu Huế',
      descriptionEn: 'Traditional Vietnamese coffee with sea salt cream',
      tags: ['Traditional', 'Vietnamese Style', 'Unique'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Arabica Cầu Đất phin', 'Kem muối biển', 'Sữa đặc'],
      customIce: true,
      customSugar: false,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'chai-cold-brew-500ml',
      name: 'Chai Cold Brew 500ml Thủy Tinh',
      nameEn: 'Cold Brew Glass Bottle 500ml',
      category: ProductCategory.coffee,
      subcategory: 'Đóng Chai Thủy Tinh & Hạt Rang',
      price: 110000,
      image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800',
      description: 'Chai thủy tinh 500ml cold brew nguyên chất, ủ lạnh 16 giờ, uống được 3-4 cốc. Trả chai được tích điểm',
      descriptionEn: '500ml bottled cold brew, 16-hour steep, returnable bottle',
      tags: ['Bottled', 'Eco-Friendly', 'Take Home'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['100% Arabica Cầu Đất', 'Nước suối mềm'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    // DESSERT
    {
      slug: 'tiramisu-matcha',
      name: 'Tiramisu Matcha Nhật Bản',
      nameEn: 'Japanese Matcha Tiramisu',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 52000,
      image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
      description: 'Lớp mascarpone mềm mịn xen kẽ bánh ladyfinger thấm matcha, rắc bột trà xanh Uji trên bề mặt',
      descriptionEn: 'Mascarpone layered with matcha-soaked ladyfingers',
      tags: ['Dessert', 'Italian Fusion', 'Limited'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Mascarpone', 'Matcha Uji', 'Ladyfinger', 'Kem tươi'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'mochi-matcha-do-dau',
      name: 'Mochi Kem Matcha Đỏ Đậu',
      nameEn: 'Matcha Red Bean Mochi',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 45000,
      image: 'https://images.unsplash.com/photo-1582716401301-b2407dc7563d?w=800',
      description: 'Vỏ mochi dai mềm bọc kem matcha và nhân đậu đỏ Nhật Bản ngọt thanh, lạnh tê',
      descriptionEn: 'Soft mochi with matcha ice cream and red bean',
      tags: ['Japanese', 'Ice Cream', 'Traditional'],
      isNew: false,
      isBestseller: true,
      inStock: true,
      ingredients: ['Mochi', 'Kem matcha', 'Đậu đỏ Hokkaido'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    // EQUIPMENT
    {
      slug: 'hop-bot-matcha-30g',
      name: 'Hộp Bột Matcha Uji 30g',
      nameEn: 'Uji Matcha Powder 30g Tin',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 380000,
      image: 'https://images.unsplash.com/photo-1629892609222-edb50d64d9fc?w=800',
      description: 'Hộp thiếc kín khí 30g matcha ceremonial grade nhập khẩu trực tiếp từ Uji, Kyoto. Đủ pha 15 chén',
      descriptionEn: 'Ceremonial grade matcha powder imported from Uji, Kyoto',
      tags: ['Import', 'JAS Organic', 'Gift Set'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['100% Matcha Uji Ceremonial'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'bo-dung-cu-chasen',
      name: 'Bộ Dụng Cụ Zen Whisk Kit',
      nameEn: 'Zen Matcha Whisk Kit',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 490000,
      image: 'https://images.unsplash.com/photo-1575638426146-e8b19c2cd8b2?w=800',
      description: 'Bộ trọn gói: Chasen tre 80 lông, Chawan gốm thủ công, Chashaku muỗng tre, hộp gỗ đựng sang trọng',
      descriptionEn: 'Complete matcha ceremony set with bamboo whisk, bowl, and scoop',
      tags: ['Premium Set', 'Gift Worthy', 'Handcrafted'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Chasen 80 prongs', 'Chawan ceramic', 'Chashaku bamboo', 'Wooden box'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    // THÊM 40+ SẢN PHẨM MỚI
    {
      slug: 'matcha-latte-hanh-nhan',
      name: 'Matcha Latte Hạnh Nhân Vàng',
      nameEn: 'Matcha Almond Milk Latte',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 62000,
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800',
      description: 'Matcha Uji xanh mượt kết hợp sữa hạnh nhân béo mịn, tạo lớp kem trắng ngàn trên nền xanh tươi',
      descriptionEn: 'Premium matcha with creamy almond milk',
      tags: ['Vegan', 'Creamy', 'Plant-based'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Sữa hạnh nhân'],
      customIce: true,
      customSugar: true,
      customMilk: ['Yến mạch', 'Hạnh nhân', 'Dừa'],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-strawberry-latte',
      name: 'Matcha Dâu Tây Latte',
      nameEn: 'Matcha Strawberry Latte',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 65000,
      image: 'https://images.unsplash.com/photo-1587080353051-466d45db54f7?w=800',
      description: 'Matcha xanh mượt với sốt dâu Đà Lạt tự nhiên, tạo màu gradient hồng xanh cuốn hút',
      descriptionEn: 'Matcha with Da Lat strawberry sauce',
      tags: ['Fruity', 'Instagram-worthy', 'New'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Sốt dâu', 'Sữa tươi'],
      customIce: true,
      customSugar: false,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-chocolate-latte',
      name: 'Matcha Chocolate Nhật Bản',
      nameEn: 'Matcha Chocolate Latte',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 68000,
      image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800',
      description: 'Matcha xanh kết hợp sô cô la đen Lindt, tạo hương vị kỳ diệu giữa xanh mát và chỉm sâu cacao',
      descriptionEn: 'Matcha meets dark chocolate from Lindt',
      tags: ['Sweet', 'Chocolate', 'Premium'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Chocolate Lindt', 'Sữa tươi'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-latte-yam',
      name: 'Matcha Khoai Lang Tím',
      nameEn: 'Matcha Purple Yam Latte',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 66000,
      image: 'https://images.unsplash.com/photo-1588732657477-8588bd7d8f0a?w=800',
      description: 'Matcha xanh với sốt khoai lang tím, tạo lớp tím huyền ảo dưới lớp xanh tươi',
      descriptionEn: 'Matcha with purple yam sauce',
      tags: ['Seasonal', 'Unique', 'Vietnamese'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Khoai lang tím', 'Sữa tươi'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-panna-cotta',
      name: 'Matcha Panna Cotta Lạnh',
      nameEn: 'Matcha Panna Cotta',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 72000,
      image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800',
      description: 'Thạch panna cotta matcha mềm mịn, phủ lớp kem tươi, topping bột matcha, vị béo thanh kỳ diệu',
      descriptionEn: 'Creamy matcha panna cotta with whipped cream',
      tags: ['Dessert Drink', 'Premium', 'Creamy'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Kem tươi', 'Gelatin'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: ['M'],
    },
    {
      slug: 'usucha-matcha-latte-mix',
      name: 'Usucha Latte Hybrid',
      nameEn: 'Usucha Latte Hybrid',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Nghi Thức (Ceremonial)',
      price: 70000,
      image: 'https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=800',
      description: '1.5g Usucha ceremonial đánh cách truyền thống, hòa quyện sữa hạnh nhân ấm áp',
      descriptionEn: 'Ceremonial Usucha blended with warm almond milk',
      tags: ['Ceremonial', 'Hybrid', 'Balanced'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Ceremonial', 'Sữa hạnh nhân'],
      customIce: false,
      customSugar: true,
      customMilk: [],
      customSize: ['M'],
    },
    {
      slug: 'matcha-iced-espresso-blend',
      name: 'Matcha Iced Espresso Blend',
      nameEn: 'Matcha Iced Espresso Blend',
      category: ProductCategory.coffee,
      subcategory: 'Cà phê Kết Hợp Matcha',
      price: 70000,
      image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800',
      description: 'Espresso đậm + matcha xanh + ice + kem lạnh, tạo độ contrast hoàn hảo giữa chua đắng và xanh mát',
      descriptionEn: 'Strong espresso meets cool matcha',
      tags: ['Fusion', 'Strong', 'Refreshing'],
      isNew: false,
      isBestseller: true,
      inStock: true,
      ingredients: ['Espresso Arabica', 'Matcha', 'Kem lạnh'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'ca-phe-ban-soi-light',
      name: 'Cà Phê Ban Sơi Light Roast',
      nameEn: 'Light Roast Ban Soi Coffee',
      category: ProductCategory.coffee,
      subcategory: 'Pha Phin & Espresso',
      price: 50000,
      image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
      description: 'Hạt cà phê từ Ban Sơi, rang nhẹ giữ nguyên aroma tự nhiên, vị chua nhẹ thoang thoảng hoa quả',
      descriptionEn: 'Light roasted Ban Soi coffee with floral notes',
      tags: ['Light Roast', 'Specialty', 'Aromatic'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Arabica Ban Sơi light roast'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'ca-phe-rang-xam-dark-roast',
      name: 'Cà Phê Rang Xám Dark Roast',
      nameEn: 'Dark Roast Premium Blend',
      category: ProductCategory.coffee,
      subcategory: 'Pha Phin & Espresso',
      price: 52000,
      image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
      description: 'Hạt cà phê blend Cầu Đất + Ban Sơi, rang đậm tạo vị đắng sâu, thích hợp pha phin chiều tối',
      descriptionEn: 'Dark roasted blend with deep flavors',
      tags: ['Dark Roast', 'Blend', 'Strong'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Arabica blend dark roast'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'affogato-matcha',
      name: 'Affogato Matcha Nóng Lạnh',
      nameEn: 'Matcha Affogato',
      category: ProductCategory.coffee,
      subcategory: 'Cà phê Kết Hợp Matcha',
      price: 75000,
      image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800',
      description: 'Kem vanilla lạnh + espresso nóng được đổ lên, kèm lớp matcha foam, trải nghiệm nóng lạnh hoàn hảo',
      descriptionEn: 'Hot espresso poured over vanilla ice cream with matcha foam',
      tags: ['Affogato', 'Dessert', 'Italian'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Espresso', 'Kem vanilla', 'Matcha foam'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: ['M'],
    },
    {
      slug: 'ca-phe-sua-da-cot-dua',
      name: 'Cà Phê Sữa Đá Cốt Dừa',
      nameEn: 'Vietnamese Coffee with Coconut Cream',
      category: ProductCategory.coffee,
      subcategory: 'Pha Phin & Espresso',
      price: 48000,
      image: 'https://images.unsplash.com/photo-1447933601403-0c6688bcccf2?w=800',
      description: 'Cà phê phin truyền thống với sữa đặc, thêm cốt dừa tươi tạo vị béo thanh độc đáo',
      descriptionEn: 'Traditional Vietnamese coffee with fresh coconut cream',
      tags: ['Traditional', 'Vietnamese', 'Creamy'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Arabica phin', 'Sữa đặc', 'Cốt dừa tươi'],
      customIce: true,
      customSugar: false,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-tonic-soda',
      name: 'Matcha Tonic Soda Xanh Mát',
      nameEn: 'Matcha Tonic Soda',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 60000,
      image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
      description: 'Matcha Uji + tonic bitter tự nhiên + soda lạnh, tạo cảm giác sảng khoái tươi tắn',
      descriptionEn: 'Matcha with natural tonic and sparkling water',
      tags: ['Soda', 'Refreshing', 'Herbal'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Tonic bitter', 'Soda lạnh'],
      customIce: true,
      customSugar: false,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-yuzu-juice',
      name: 'Matcha Yuzu Juice Đắm Mát',
      nameEn: 'Matcha Yuzu Fresh Juice',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 58000,
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800',
      description: 'Matcha xanh mướt + nước yuzu Nhật Bản chua ngọt, tạo vị kỳ diệu giữa xanh tươi và vàng nhạt',
      descriptionEn: 'Matcha blended with Japanese yuzu juice',
      tags: ['Juice', 'Japanese', 'Citrus'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Matcha Uji', 'Yuzu Nhật Bản', 'Nước lọc'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'matcha-latte-hot-warm',
      name: 'Matcha Latte Nóng Ấm',
      nameEn: 'Hot Matcha Latte',
      category: ProductCategory.matcha,
      subcategory: 'Matcha Latte & Sáng Tạo',
      price: 62000,
      image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800',
      description: 'Matcha xanh đánh foam tương truyền, hòa quyện sữa tươi ấm, tạo tách trà Nhật đầy ấm áp mỗi sáng',
      descriptionEn: 'Hot matcha latte with steamed milk',
      tags: ['Hot Drink', 'Morning', 'Comfort'],
      isNew: false,
      isBestseller: true,
      inStock: true,
      ingredients: ['Matcha Uji', 'Sữa tươi ấm'],
      customIce: false,
      customSugar: true,
      customMilk: [],
      customSize: ['M'],
    },
    {
      slug: 'tiramisu-coffee-latte',
      name: 'Tiramisu Coffee Latte',
      nameEn: 'Tiramisu Coffee Latte',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 60000,
      image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
      description: 'Vị cà phê đậm + mascarpone mịn + cocoa powder, tái hiện hương vị tiramisu trong một cốc lạnh mắt',
      descriptionEn: 'Tiramisu flavored coffee latte',
      tags: ['Dessert', 'Coffee', 'Italian'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Coffee espresso', 'Mascarpone', 'Cocoa'],
      customIce: true,
      customSugar: false,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'mochi-chocolate-ice-cream',
      name: 'Mochi Kem Chocolate Đen',
      nameEn: 'Dark Chocolate Mochi',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 48000,
      image: 'https://images.unsplash.com/photo-1582716401301-b2407dc7563d?w=800',
      description: 'Vỏ mochi dai mềm bọc kem chocolate đen Lindt 70%, lạnh tê, vị cacao tươi mát',
      descriptionEn: 'Soft mochi with dark chocolate ice cream',
      tags: ['Dessert', 'Chocolate', 'Japanese'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Mochi', 'Kem chocolate đen', 'Lindt 70%'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'mochi-strawberry-vanilla',
      name: 'Mochi Dâu - Vani Lạnh',
      nameEn: 'Strawberry Vanilla Mochi',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 46000,
      image: 'https://images.unsplash.com/photo-1582716401301-b2407dc7563d?w=800',
      description: 'Mochi dai mềm với lõi kem vani tự nhiên, phủ lớp dâu tây Đà Lạt tươi, hương thơm dâu nhẹ nhàng',
      descriptionEn: 'Mochi with vanilla cream and fresh strawberry',
      tags: ['Dessert', 'Strawberry', 'Fresh'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Mochi', 'Kem vani', 'Dâu tây'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'dorayaki-matcha-red-bean',
      name: 'Dorayaki Matcha Đậu Đỏ',
      nameEn: 'Matcha Red Bean Dorayaki',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 52000,
      image: 'https://images.unsplash.com/photo-1590869572320-ca47d2c4efb2?w=800',
      description: 'Bánh dorayaki mềm mặn với nhân đậu đỏ ngọt, phủ lớp matcha xanh, vị cân bằng giữa ngọt mặn',
      descriptionEn: 'Soft dorayaki with matcha and red bean filling',
      tags: ['Japanese Dessert', 'Matcha', 'Traditional'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Bột bánh', 'Matcha', 'Đậu đỏ'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'croissant-matcha-butter',
      name: 'Croissant Matcha Butter',
      nameEn: 'Matcha Butter Croissant',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 55000,
      image: 'https://images.unsplash.com/photo-1585331066969-e4238cf3854d?w=800',
      description: 'Croissant bơ tươi giòn, nhân matcha kem butter mịn, tạo vị béo ngậu kỳ diệu',
      descriptionEn: 'Crispy croissant with matcha butter cream',
      tags: ['Pastry', 'French', 'Matcha'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Bơ tươi', 'Bột mì', 'Matcha', 'Kem butter'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'brownie-matcha-swirl',
      name: 'Brownie Matcha Swirl',
      nameEn: 'Matcha Swirl Brownie',
      category: ProductCategory.dessert,
      subcategory: null,
      price: 58000,
      image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800',
      description: 'Brownie chocolate đậm với vạch matcha xanh swirl, tạo contrast đẹp mắt và hương vị đối lập',
      descriptionEn: 'Rich chocolate brownie with matcha swirl',
      tags: ['Brownie', 'Chocolate', 'Artistic'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Chocolate', 'Matcha', 'Trứng', 'Bơ'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'latte-cao-su-tao-bac',
      name: 'Latte Cao Su Táo Bắc',
      nameEn: 'Latte with Ginseng Apple',
      category: ProductCategory.coffee,
      subcategory: 'Pha Phin & Espresso',
      price: 62000,
      image: 'https://images.unsplash.com/photo-1447933601403-0c6688bcccf2?w=800',
      description: 'Espresso + sữa tươi + cao su Tây Bắc + táo Bắc, tạo vị giải độc, bổ thận độc đáo',
      descriptionEn: 'Latte infused with ginseng and northern apples',
      tags: ['Herbal', 'Wellness', 'Vietnamese'],
      isNew: true,
      isBestseller: false,
      inStock: true,
      ingredients: ['Espresso', 'Sữa tươi', 'Cao su', 'Táo Bắc'],
      customIce: true,
      customSugar: true,
      customMilk: [],
      customSize: ['M', 'L'],
    },
    {
      slug: 'cold-brew-concentrate-bottle',
      name: 'Chai Cold Brew Concentrate 250ml',
      nameEn: 'Cold Brew Concentrate 250ml',
      category: ProductCategory.coffee,
      subcategory: 'Đóng Chai Thủy Tinh & Hạt Rang',
      price: 85000,
      image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800',
      description: 'Cold brew concentrate cô đặc 250ml, pha đôi với sữa hoặc nước để tạo 2 cốc cold brew',
      descriptionEn: 'Concentrated cold brew for making 2 servings',
      tags: ['Concentrate', 'Convenient', 'Value'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['100% Arabica concentrate'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'matcha-powder-premium-100g',
      name: 'Bột Matcha Premium 100g',
      nameEn: 'Premium Matcha Powder 100g',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 950000,
      image: 'https://images.unsplash.com/photo-1629892609222-edb50d64d9fc?w=800',
      description: 'Hộp thiếc 100g matcha ceremonial grade + lý gốm + muỗng tre. Đủ pha 50 chén. Quà tặng cao cấp',
      descriptionEn: 'Premium set with 100g matcha, ceramic cup, and bamboo scoop',
      tags: ['Gift Set', 'Premium', 'Complete'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['100% Matcha Uji Premium 100g', 'Ceramic bowl', 'Bamboo scoop'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'matcha-tea-set-luxury',
      name: 'Bộ Trà Matcha Luxury 5 Piece',
      nameEn: 'Luxury Matcha Tea Set 5 Pieces',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 1200000,
      image: 'https://images.unsplash.com/photo-1575638426146-e8b19c2cd8b2?w=800',
      description: 'Bộ 5 món: Hộp bột 50g + Chasen + Chawan + Chashaku + Bộ bàn tre. Tặng hộp quà màu vàng sang trọng',
      descriptionEn: 'Complete luxury set with 50g matcha and tea utensils',
      tags: ['Luxury', 'Gift', 'Handcrafted'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['50g Matcha', 'Full tea set', 'Bamboo stand', 'Luxury gift box'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'coffee-bean-bag-250g',
      name: 'Túi Hạt Cà Phê Ban Sơi 250g',
      nameEn: 'Ban Soi Coffee Beans 250g Bag',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 180000,
      image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=800',
      description: 'Hạt cà phê Ban Sơi rang xám, đóng túi kraft hít khí 250g, dùng cho phin gia đình 2 tuần',
      descriptionEn: 'Ban Soi roasted coffee beans 250g',
      tags: ['Beans', 'Take Home', 'Fresh'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['100% Arabica Ban Sơi beans'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'coffee-bean-premium-blend-250g',
      name: 'Túi Hạt Blend Premium 250g',
      nameEn: 'Premium Coffee Blend 250g Bag',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 200000,
      image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=800',
      description: 'Blend Cầu Đất + Ban Sơi rang xám đặc biệt, 250g, vị cân bằng giữa xanh vị cà phê tinh tế',
      descriptionEn: 'Specialty blend 250g for premium coffee experience',
      tags: ['Premium', 'Blend', 'Specialty'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Arabica blend premium'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'french-press-850ml',
      name: 'French Press Bodum 850ml',
      nameEn: 'Bodum French Press 850ml',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 520000,
      image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800',
      description: 'Bình pha French Press thủy tinh Bodum 850ml, dung tích cho 8 tách, tặng thìa đo cà phê',
      descriptionEn: 'Bodum glass French press for 8 cups',
      tags: ['Equipment', 'Premium', 'Home Brewing'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Bodum glass', 'Steel filter', 'Measuring spoon'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
    {
      slug: 'grinder-manual-coffee',
      name: 'Máy Xay Cà Phê Cầm Tay',
      nameEn: 'Manual Coffee Grinder',
      category: ProductCategory.equipment,
      subcategory: null,
      price: 380000,
      image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=800',
      description: 'Máy xay cà phê cầm tay, dễ dàng điều chỉnh độ hạt, tương thích phin và French press',
      descriptionEn: 'Adjustable manual coffee grinder',
      tags: ['Equipment', 'Manual', 'Portable'],
      isNew: false,
      isBestseller: false,
      inStock: true,
      ingredients: ['Stainless steel burrs', 'Glass jar'],
      customIce: false,
      customSugar: false,
      customMilk: [],
      customSize: [],
    },
  ]

  for (const product of productData) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: product,
    })
  }
  console.log(`✅ ${productData.length} products created`)

  // ─── LOCATIONS ───────────────────────────────────────────────────────────────
  const locationData = [
    {
      slug: 'hcm-flagship',
      name: 'TP.HCM Flagship Store',
      address: '128 Vườn Xanh, P. Bến Nghé',
      district: 'Quận 1',
      city: 'TP. Hồ Chí Minh',
      phone: '+84 (28) 3990 9988',
      hours: '07:00 - 22:00 (Thứ 2 - Chủ nhật)',
      features: ['Chỗ đỗ ô tô', 'Sân vườn Zen', 'Phòng trà đạo', 'Workshop cuối tuần'],
      image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
      lat: 10.7769,
      lng: 106.7009,
    },
    {
      slug: 'hanoi-west-lake',
      name: 'Hà Nội Tây Hồ',
      address: '45 Đường Trúc Bạch',
      district: 'Quận Ba Đình',
      city: 'Hà Nội',
      phone: '+84 (24) 3715 8899',
      hours: '07:30 - 22:00 (Thứ 2 - Chủ nhật)',
      features: ['View Hồ Tây', 'Không gian yên tĩnh', 'Phòng trà đạo', 'Outdoor seating'],
      image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
      lat: 21.0453,
      lng: 105.8251,
    },
    {
      slug: 'danang-city',
      name: 'Đà Nẵng Trung Tâm',
      address: '15 Đường Lê Lợi',
      district: 'Quận Hải Châu',
      city: 'Đà Nẵng',
      phone: '+84 (236) 3888 777',
      hours: '07:00 - 22:00 (Thứ 2 - Chủ nhật)',
      features: ['Không gian mở', 'View sông Hàn', 'Gần biển', 'Matcha bar counter'],
      image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
      lat: 16.0544,
      lng: 108.2022,
    },
  ]

  for (const loc of locationData) {
    await prisma.location.upsert({
      where: { slug: loc.slug },
      update: {},
      create: loc,
    })
  }
  console.log(`✅ ${locationData.length} locations created`)

  // ─── COUPONS ─────────────────────────────────────────────────────────────────
  const couponData = [
    {
      code: 'MODTRAFIRST',
      discountPercent: 15,
      minOrderValue: 0,
      maxUses: 1000,
      isActive: true,
    },
    {
      code: 'MATCHA10',
      discountPercent: 10,
      minOrderValue: 100000,
      maxUses: 500,
      isActive: true,
    },
    {
      code: 'SUMMER20',
      discountPercent: 20,
      minOrderValue: 200000,
      maxUses: 200,
      isActive: true,
    },
  ]

  for (const coupon of couponData) {
    await prisma.coupon.upsert({
      where: { code: coupon.code },
      update: {},
      create: coupon,
    })
  }
  console.log(`✅ ${couponData.length} coupons created`)

  // ─── USPs ────────────────────────────────────────────────────────────────────
  const uspData = [
    {
      title: '100% Ceremonial Matcha Uji Kyoto',
      description: 'Chuẩn JAS Organic, búp trà Tencha che bóng 30 ngày, vị umami đậm đà tự nhiên không hương liệu',
      icon: 'leaf',
      sortOrder: 1,
    },
    {
      title: 'Nghiền Cối Đá Granit 30g/giờ',
      description: 'Quy trình thủ công siêu chậm giữ nguyên hương thơm và dinh dưỡng, mịn như phấn tơ',
      icon: 'settings',
      sortOrder: 2,
    },
    {
      title: 'Bao Bì Sinh Học & Ly Bã Mía',
      description: 'Cam kết 0% nhựa dùng một lần, túi kraft tái chế, muỗng gỗ phân hủy 100% tự nhiên',
      icon: 'recycle',
      sortOrder: 3,
    },
  ]

  for (const usp of uspData) {
    await prisma.uSP.upsert({
      where: { id: `usp-${usp.sortOrder}` },
      update: {},
      create: { id: `usp-${usp.sortOrder}`, ...usp },
    })
  }
  console.log(`✅ ${uspData.length} USPs created`)

  console.log('\n🌱 Seeding completed successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
